plugins {
    id 'com.android.application'
}

android {
    namespace 'com.finan.needlegap'
    compileSdk 35

    defaultConfig {
        applicationId 'com.finan.needlegap'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }
}

dependencies {
    implementation 'com.google.android.gms:play-services-ads:25.4.0'
}
